### ISSUE TITLE
More options for Javascript

### ISSUE THREAD

**Issue by aaferrari** [slosd/guiconfig#36]
Some time ago there was an extension called [Javascript Options](http://wayback.archive.org/web/20141204230117/https://addons.mozilla.org/en-US/firefox/addon/javascript-options/) that allows to modify the following parameters:
<table cellpadding="2" cellspacing="2" >
   <thead><tr >
    <th>Label (as it appeared in the configuration panel)</th>
    <th>Option</th>
    <th>Type</th>
    <th>Default value</th>
    <th>Description<a href="http://kb.mozillazine.org/About:config_entries">¹</a></th>
   </tr></thead>
<tbody>
   <tr >
    <td>Change the status bar text</td>
    <td><tt>dom.disable_window_status_change</tt></td>
    <td rowspan=3>Boolean</td>
    <td>True</td>
    <td>Prevent javascript set messages in status bar.</td>

   </tr>
   <tr >
    <td>Change images</td>
    <td><tt>dom.disable_image_src_set</tt></td>

    <td >False</td>
    <td>Determines if the <tt>src</tt> atrrib in images can be changed via JavaScript.</td>
   </tr>
   <tr >
    <td>Close windows</td>
    <td><tt>dom.allow_scripts_to_close_windows</tt></td>

    <td >False</td>
    <td>Closes a window with Javascript, when the value is False only windows created by scripts can be closed.</td>
   </tr>
   <tr >
       <td>It consisted of a form with checkboxes that allows to modify this property as follows:</br>
       <ul><li>Change (applies to most form items): <tt>change</tt></li>
<li>Mouse button click: <tt>click</tt></li>
<li>Mouse button double click: <tt>dblclick</tt></li>
<li>Mouse button press: <tt>mousedown</tt></li>
<li>Mouse button release: <tt>mouseup</tt></li>
<li>Form reset: <tt>reset</tt></li>
<li>Form submit: <tt>submit</tt></li></ul></td>
    <td><tt>dom.popup_allowed_events</tt></td>
    <td>String</td>
    <td >change click dblclick mouseup notificationclick reset submit touchend</td>
    <td >A space-separated list of the events that are allowed to create popups. A presumably complete list of events is <a href="http://lxr.mozilla.org/mozilla/source/content/events/src/nsDOMEvent.cpp">here</a> (outdated).</td>
   </tr>
   </tbody>
  </table>
Unfortunately, this extension is not updated for years (seems to me that it only works on older versions of Firefox prior to 4) so I think that would be useful add these options in guiconfig (perhaps in the section "Permissions").

**Comment by slosd** [comment]
Thanks for the detailed list. I will add these except for `dom.disable_image_src_set` which was removed recently (https://bugzilla.mozilla.org/show_bug.cgi?id=773429).
