### ISSUE TITLE
flag for multiprocess - not working as of v54.0 (64-bit)

### ISSUE THREAD

**Issue by mentalpiracy** [slosd/guiconfig#42]
I can see from code view that you made the update ~10 months ago to set flag for multiprocess compatibility, but Compatibility Reporter is presently flagging guiconfig as non-compatible.

Not sure if this is just an issue unique to 54.0 (64-bit) or for v54.0 generally

**Comment by slosd** [comment]
You are correct. I never released a version with the compatibility flag set, but a new version is in the review queue now and should be available soon.
